name: flutter_routes_poc
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Link: https://pub.dev/packages/auto_route
  auto_route: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito:
  build_runner:
  flutter_lints:
  auto_route_generator:

flutter:
  uses-material-design: true
