name: flutter_routes_poc
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # https://pub.dev/packages/fluro
  fluro: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  mockito: ^5.0.17
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
